language: java
git:
  depth: 3
branches:
  only:
    - develop
jdk:
  - oraclejdk8
#install:  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pno-repo-man
#test: mvn test -B -Pno-repo-man
